laravel/app/routes.php
<?php

Route::get('/', array('as' => 'home', 'uses' => 'HomeController@index'));
Route::get('/home', array('as' => 'home', 'uses' => 'HomeController@index'));
Route::get('empresa', array('as' => 'quemsomos', 'uses' => 'QuemsomosController@index'));
Route::get('empresa/quemsomos', array('as' => 'quemsomos', 'uses' => 'QuemsomosController@index'));
Route::get('empresa/diferenciais', array('as' => 'diferenciais', 'uses' => 'DiferenciaisController@index'));
Route::get('solucoes/executive_search', array('as' => 'executive_search', 'uses' => 'SolucoesExecController@index'));
Route::get('solucoes/executive_search/{slug?}', array('as' => 'executive_search', 'uses' => 'SolucoesExecController@detalhes'));
Route::get('solucoes/desenvolvimento_organizacional', array('as' => 'desenvolvimento_organizacional', 'uses' => 'SolucoesDevController@index'));
Route::get('solucoes/desenvolvimento_organizacional/{slug?}', array('as' => 'desenvolvimento_organizacional', 'uses' => 'SolucoesDevController@detalhes'));
Route::get('oportunidades', array('as' => 'oportunidades', 'uses' => 'OportunidadesController@index'));
Route::get('oportunidades/detalhe/{slug?}', array('as' => 'oportunidades', 'uses' => 'OportunidadesController@detalhe'));
Route::post('oportunidades/enviar', array('as' => 'oportunidades.enviar', 'uses' => 'OportunidadesController@enviar'));
Route::get('cases', array('as' => 'cases', 'uses' => 'CasesController@index'));
Route::get('cases/cases', array('as' => 'cases', 'uses' => 'CasesController@index'));
Route::get('cases/depoimentos', array('as' => 'cases.depoimentos', 'uses' => 'DepoimentosController@index'));
Route::get('contato', array('as' => 'contato', 'uses' => 'ContatoController@index'));
Route::post('contato/enviar', array('as' => 'contato.enviar', 'uses' => 'ContatoController@enviar'));

/* LOCALIZAÇÃO */
Route::get('idioma/{sigla_idioma?}', function($sigla_idioma){
	if($sigla_idioma == 'pt' || $sigla_idioma == 'en')
		Session::put('locale', $sigla_idioma);
	
	return Redirect::back();
});



Route::get('painel', array('before' => 'auth', 'as' => 'painel.home', 'uses' => 'Painel\HomeController@index'));
Route::get('painel/login', array('as' => 'painel.login', 'uses' => 'Painel\HomeController@login'));

// Autenticação do Login
Route::post('painel/login',  array('as' => 'painel.auth', function(){
	$authvars = array(
		'username' => Input::get('username'),
		'password' => Input::get('password')
	);

	$lembrar = (Input::get('lembrar') == '1') ? true : false;

	if(Auth::attempt($authvars, $lembrar)){
		return Redirect::to('painel');
	}else{
		Session::flash('login_errors', true);
		return Redirect::to('painel/login');
	}
}));

Route::get('painel/logout', array('as' => 'painel.off', function(){
	Auth::logout();
	return Redirect::to('painel');
}));

Route::post('ajax/gravaOrdem', array('before' => 'auth', 'uses' => 'Painel\AjaxController@gravaOrdem'));

Route::group(array('prefix' => 'painel', 'before' => 'auth'), function()
{
	Route::get('downloadCV/{id}', function($id){

		$candidato = Candidato::find($id);
		
		return Response::download(base_path('curriculos/'.$candidato->curriculo));
	});

	Route::post('candidatos/buscarNome', array('as' => 'painel.buscacandidato.nome', 'uses' => 'Painel\CandidatosController@buscarNome'));
	Route::post('candidatos/buscarData', array('as' => 'painel.buscacandidato.data', 'uses' => 'Painel\CandidatosController@buscarData'));

    Route::resource('usuarios', 'Painel\UsuariosController');
    Route::resource('banners', 'Painel\BannersController');
	Route::resource('quemsomos', 'Painel\QuemSomosController');
	Route::resource('equipe', 'Painel\EquipeController');
	Route::resource('diferenciais', 'Painel\DiferenciaisController');
	Route::resource('solucoesexec', 'Painel\SolucoesExecController');
	Route::resource('solucoesdev', 'Painel\SolucoesDevController');
	Route::resource('cursos', 'Painel\CursosController');
	Route::resource('oportunidades', 'Painel\OportunidadesController');
	Route::resource('oportunidadesarquivadas', 'Painel\OportunidadesArquivadasController');
	Route::resource('candidatos', 'Painel\CandidatosController');
	Route::resource('cases', 'Painel\CasesController');
	Route::resource('depoimentos', 'Painel\DepoimentosController');
	Route::resource('contato', 'Painel\ContatoController');
	Route::resource('solucoes', 'Painel\SolucoesController');
//NOVASROTASDOPAINEL//
});

laravel/app/views/backend/templates/index.blade.php
<!DOCTYPE html>
<html lang="pt-BR" class="no-js">
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="robots" content="index, nofollow" />
    <meta name="author" content="Trupe Design" />
    <meta name="copyright" content="2013 Trupe Design" />
    <meta name="viewport" content="width=device-width,initial-scale=1">
    
    <title>Meta Executivos - Painel Administrativo</title>
	<meta name="description" content="">
    <meta name="keywords" content="" />
    
	<base href="{{ url() }}/">
	<script>var BASE = "{{ url() }}"</script>

	<?=Assets::CSS(array(
		'vendor/reset-css/reset',
		'css/fontface/stylesheet',
		'vendor/jquery-ui/themes/base/jquery-ui',
		'vendor/bootstrap/dist/css/bootstrap.min',
		'css/painel/painel'
	))?>

	@if(isset($css))
		<?=Assets::CSS(array($css))?>
	@endif

	<script src="//ajax.googleapis.com/ajax/libs/jquery/2.1.0/jquery.min.js"></script>
	<script>window.jQuery || document.write('<script src="assets/vendor/jquery/dist/jquery.min.js"><\/script>')</script>

	@if(App::environment()=='local')
		<?=Assets::JS(array('js/vendor/modernizr/modernizr', 'vendor/less.js/dist/less-1.6.2.min'))?>
	@else
		<?=Assets::JS(array('js/vendor/modernizr/modernizr'))?>
	@endif

</head>
	<body @if(Route::currentRouteName() == 'painel.login') class="body-painel-login" @else class="body-painel" @endif >

		@if(Route::currentRouteName() != 'painel.login')

			<nav class="navbar navbar-default">
				<div class="navbar-inner">
					<a href="{{URL::route('painel.home')}}" title="Página Inicial" class="navbar-brand">Meta Executivos</a>

					<ul class="nav navbar-nav">

						<li @if(str_is('painel.home*', Route::currentRouteName())) class="active" @endif >
							<a href="{{URL::route('painel.home')}}" title="Início">Início</a>
						</li>

						<li @if(str_is('painel.banner*', Route::currentRouteName())) class="active" @endif >
							<a href="{{URL::route('painel.banners.index')}}" title="Banners">Banners</a>
						</li>

						<li class="dropdown @if(str_is('painel.quemsomos*', Route::currentRouteName()) || str_is('painel.equipe*', Route::currentRouteName()) || str_is('painel.diferenciais*', Route::currentRouteName())) active @endif">
							<a href="#" title="Com Dropdown" class="dropdown-toggle" data-toggle="dropdown">Empresa <b class="caret"></b></a>
							<ul class="dropdown-menu">
								<li><a href="{{URL::route('painel.quemsomos.index')}}" title="Quem Somos">Quem Somos</a></li>
								<li><a href="{{URL::route('painel.equipe.index')}}" title="Equipe">Equipe</a></li>
								<li><a href="{{URL::route('painel.diferenciais.index')}}" title="Diferenciais">Diferenciais</a></li>								
							</ul>
						</li>

						<li class="dropdown @if(str_is('painel.solucoes*', Route::currentRouteName()) || str_is('painel.cursos*', Route::currentRouteName())) active @endif">
							<a href="#" title="Com Dropdown" class="dropdown-toggle" data-toggle="dropdown">Soluções <b class="caret"></b></a>
							<ul class="dropdown-menu">
								<li><a href="{{URL::route('painel.solucoesexec.index')}}" title="Executive Search">Executive Search</a></li>
								<li><a href="{{URL::route('painel.solucoesdev.index')}}" title="Desenvolvimento Organizacional">Desenvolvimento Organizacional</a></li>
							</ul>
						</li>

						<li class="dropdown @if(str_is('painel.oportunidades*', Route::currentRouteName()) || str_is('painel.candidatos*', Route::currentRouteName())  || str_is('painel.buscacandidato*', Route::currentRouteName())) active @endif">
							<a href="#" title="Com Dropdown" class="dropdown-toggle" data-toggle="dropdown">Oportunidades <b class="caret"></b></a>
							<ul class="dropdown-menu">
								<li><a href="{{URL::route('painel.oportunidades.index')}}" title="Oportunidades Ativas">Oportunidades Ativas</a></li>
								<li><a href="{{URL::route('painel.oportunidadesarquivadas.index')}}" title="Oportunidades Arquivadas">Oportunidades Arquivadas</a></li>
								<li class="divider"></li>
								<li><a href="{{URL::route('painel.candidatos.index')}}" title="Candidatos">Candidatos</a></li>
							</ul>
						</li>

						<li class="dropdown @if(str_is('painel.cases*', Route::currentRouteName()) || str_is('painel.depoimentos*', Route::currentRouteName())) active @endif">
							<a href="#" title="Com Dropdown" class="dropdown-toggle" data-toggle="dropdown">Cases <b class="caret"></b></a>
							<ul class="dropdown-menu">
								<li><a href="{{URL::route('painel.cases.index')}}" title="Cases">Cases</a></li>
								<li><a href="{{URL::route('painel.depoimentos.index')}}" title="Depoimentos">Depoimentos</a></li>								
							</ul>
						</li>

						<li @if(str_is('painel.contato*', Route::currentRouteName())) class="active" @endif >
							<a href="{{URL::route('painel.contato.index')}}" title="Contato">Contato</a>
						</li>

						<li class="dropdown @if(str_is('painel.usuarios*', Route::currentRouteName())) active @endif">
							<a href="#" title="Com Dropdown" class="dropdown-toggle" data-toggle="dropdown">Sistema <b class="caret"></b></a>
							<ul class="dropdown-menu">
								<li><a href="{{URL::route('painel.usuarios.index')}}" title="Usuários do Painel">Usuários</a></li>
								<li><a href="{{URL::route('painel.off')}}" title="Logout">Logout</a></li>
							</ul>
						</li>

					</ul>
				</div>
			</nav>

		@endif

		<div class="main {{ 'main-'.str_replace('.', '-', Route::currentRouteName()) }}">
			@yield('conteudo')
		</div>
		
		<footer>
			<div class="container">
				<a href="http://www.trupe.net" target="_blank" title="Criação de Sites : Trupe Agência Criativa">© Criação de Sites : Trupe Agência Criativa</a>
			</div>
		</footer>

		@if(Route::currentRouteName() == 'painel.login')
			<?=Assets::JS(array(
				'vendor/jquery-ui/ui/minified/jquery-ui.min',
				'vendor/bootbox/bootbox',
				'vendor/ckeditor/ckeditor',
				'vendor/ckeditor/adapters/jquery',
				'vendor/ckeditor/config',
				'vendor/bootstrap/dist/js/bootstrap.min',
				'js/painel/login'
			))?>
		@else
			<?=Assets::JS(array(
				'vendor/jquery-ui/ui/minified/jquery-ui.min',
				'vendor/bootbox/bootbox',
				'vendor/ckeditor/ckeditor',
				'vendor/ckeditor/adapters/jquery',
				'vendor/ckeditor/config',
				'vendor/bootstrap/dist/js/bootstrap.min',
				'js/painel/painel'
			))?>
		@endif

	</body>
</html>